version: 2
mergeable:
    - when: pull_request.*, pull_request_review.*
      name: "Approval check"
      validate:
        - do: commit
          message:
            regex: '^(feat|docs|chore|fix|refactor|test|style|perf)(\(\w+\))?:.+$'
            message: 'Custom message' # Semantic release conventions must be followed
            skip_merge: true # Optional, Default is true. Will skip commit with message that includes 'Merge'
            oldest_only: false # Optional, Default is false. Only check the regex against the oldest commit
            newest_only: false # Optional, Default is false. Only check the regex against the newest commit
            single_commit_only: false # Optional, Default is false. only process this validator if there is one commit
            message_type: '' # Optional, only check regex against the field specified. Default is '', which processes the 'message' field. Can also be set to 'author_email' or 'committer_email'
          - do: approvals
            min:
                count: 0
            limit:
                users: ["BAbate", "kirubeltadesse", "Roberamelaek", "dinaolmelak", "Getnet12"]
            required:
                reviewers: ["Roberamelaek", "dinaolmelak","kirubeltadesse"]
